baseURL : https://sengov.com/
languageCode : en-us
title : Contact United States Senators and Governors
author : john
taxonomies: ""
pygmentsstyle: default
PygmentsCodeFences: true
disqusShortname: sengov
theme: "sengov"
